# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
   
name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: trial-cluster    # Add your cluster name here.
  GKE_ZONE: europe-west2  # Add your cluster zone here.
  DEPLOYMENT_NAME: python-app # Add your deployment name here.
  IMAGE: python-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
          #create_credentials_file: 'true'
          workload_identity_provider: 'projects/1044325156148/locations/global/workloadIdentityPools/scopeit/providers/demo-pool'
          service_account: 'service-trial1@hidden-phalanx-375513.iam.gserviceaccount.com'
          
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
 
    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        
    # Deploy sample image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f deployment.yml
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
