name: 'Promote'
on:
  workflow_dispatch


jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'

    - name: 'Deploy'
      # Parameters are pulled directly from the GitHub deployment event so the
      # configuration for the job here is very minimal.
      uses: 'srikantharun/help-with-helm@master'
      with:
        release: 'production-myapp'
        namespace: 'default'
        token: '${{ github.token }}'
        secrets: '${{ toJSON(secrets) }}'
        version: '${{ github.sha }}'
        chart: 'app'
        remove_canary: true
        track: stable
        value_files: '["./config/production.yml","./config/_common.yml"]'
        helm: helm3
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
